# Generated by Django 4.1.2 on 2024-05-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_feedback_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created',)},
        ),
    ]
